DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS DOG;

CREATE TABLE PERSON (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR (255) NOT NULL,
    LAST_NAME VARCHAR (255),
    DOG_ID INTEGER,
    PRIMARY KEY (ID)
);

CREATE TABLE DOG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR (255) NOT NULL,
    PRIMARY KEY (ID)
);